import 'package:ahtizam/src/features/my_order_details/domain/model/my_order_details_model.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'my_order_details_controller.g.dart';  // This part file will be generated by the build_runner

@riverpod
class MyOrderDetailsController extends _$MyOrderDetailsController {
  @override
  MyOrderDetailsModel build() {
    return const MyOrderDetailsModel(
      driverName: 'سالم',
      driverRating: '4.5',
      vehicleType: 'شاحنة',
      vehicleId: 'KE232',
      orderStart: 'شارع ألف',
      orderEnd: 'شارع ألف',
      date: '20 أكتوبر 23',
      price: 50.0,
      paymentMethod: 'أبل باي', driverImage: '', orderNumber: '32r563', orderTimeStart: '11:00', orderTimeEnd: '12:30',
    );
  }

  void updateOrderDetails(MyOrderDetailsModel newOrderDetails) {
    state = newOrderDetails;
  }
}
