default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --split-per-abi --no-tree-shake-icons"

    firebase_app_distribution(
      app: "1:438670902644:android:fbc2c6245d27f601dcd821",
      firebase_cli_token: "1//0e-Y4CVs1Fh7lCgYIARAAGA4SNwF-L9IrEn3ioxUoP3KIHlCszL8477Kg_0ko9y6-0ldWoJp9YSGcFW6Vx03Ks8y0U8Vb8xtLFBA",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk",
      testers: "mouazhariry5@gmail.com,moh.allaaadeen@gmail.com",
      release_notes: "Handle Chat and payment and order status flow"
    )
  end
end

# ENV["FIREBASE_TOKEN"]