default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --split-per-abi --no-tree-shake-icons"

    firebase_app_distribution(
      app: "1:438670902644:android:fbc2c6245d27f601dcd821",
      firebase_cli_token: "1//09RZYAFtFdl-9CgYIARAAGAkSNwF-L9Ir6oYCbfCN3o0OhaC7pjqakSwgvukLOyGberZsojXCz3W9cbeIkWwuqSzSEJO-RkBDoWE",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk",
      testers: "mouazhariry5@gmail.com,moh.allaaadeen@gmail.com",
      release_notes: "New release change quick order flow ."
    )
  end
end
